### ISSUE TITLE
StallGuard

### ISSUE THREAD

**Issue by 1iverea9er** [slimcdk/esphome-custom-components#11]
Hi
I can't run the StallGuard function.

I noticed that according to the your [readme.md](https://github.com/slimcdk/esphome-custom-components/tree/master/esphome/components/tmc2209#readme), the condition for triggering the StallGuard function is the following formula:
`(510 - SG_RESULT) /( 510 - SGTHRS * 2) = load coefficient`.

My driver outputs `SG_RESULT` values from 0 to 90 (approximately), which does not match the dataset (where the value is in the range 0...510)

I have set the value `SGTHRS=0` to offset this discrepancy. But it does not  solves the problem. Because the value `SG_RESULT=0`  -> `load=100%` appears even if the motor is spinning without load. 

I also noticed that according to the dataset, the condition for triggering the StallGuard function is the different formula:
 `SG_RESULT = SGTHRS*2`. 

in general, my problem is inadequate values of `SG_RESULT`.

I have a few questions.
Could my problems be related to a specific modification of the driver that I used / or motor? 
Why do I get `SG_RESULT` values no more than 90 (approximately)?
Why does the `SG_RESULT` value drop to 0 when motor run without load?

My config:
```
external_components:
  - source: github://slimcdk/esphome-custom-components
    components: [ tmc2209, stepper ]

esphome:
  name: trv-exp-stepper
  friendly_name: TRV EXP Stepper
  on_boot:
    - tmc2209.configure:
        microsteps: 8
        interpolation: true
        enable_spreadcycle: false
    - tmc2209.stallguard:
        threshold: 50
    - tmc2209.currents:
        standstill_mode: freewheeling
        irun: 16
        ihold: 0
        tpowerdown: 0
        iholddelay: 0

...


uart:
  tx_pin: GPIO22
  rx_pin: GPIO23
  baud_rate: 500000 # 9600 -> 500k

button:
  - platform: template
    name: Stop
    on_press:
      - stepper.stop: driver

  - platform: template
    name: 1000 Steps forward
    on_press:
      - stepper.set_target:
          id: driver
          target: !lambda return id(driver)->current_position +1000;

  - platform: template
    name: 1000 Steps backward
    on_press:
      - stepper.set_target:
          id: driver
          target: !lambda return id(driver)->current_position -1000;

number:
  - platform: template
    name: Target position
    min_value: -100000
    max_value: 100000
    step: 100
    lambda: return id(driver)->current_position;
    update_interval: 1s
    set_action:
      - stepper.set_target:
          id: driver
          target: !lambda "return x;"

  - platform: template
    name: StallGuard Threshold
    min_value: 0
    max_value: 255
    optimistic: true
    step: 1
    set_action:
      - tmc2209.stallguard:
          threshold: !lambda "return x;"

stepper:
  - platform: tmc2209
    id: driver
    max_speed: 1500 steps/s
    acceleration: 250 steps/s^2
    deceleration: 250 steps/s^2
    #address: 0x00
    enn_pin: GPIO19
    diag_pin: GPIO33
    #index_pin: GPIO32
    step_pin: GPIO5
    dir_pin: GPIO18
    rsense: 110 mOhm
    vsense: False
    ottrim: 0
    on_stall:
        - logger.log: "Motor stalled!"
        - stepper.stop: driver



sensor:
  - platform: tmc2209
    type: stallguard_result
    name: Driver stallguard
    update_interval: 250ms

  - platform: tmc2209
    type: motor_load
    name: Motor load
    update_interval: 250ms

  - platform: tmc2209
    type: actual_current
    name: Actual current
    update_interval: 250ms

```

I used this driver
![image](https://github.com/user-attachments/assets/7ef28bb8-a3d1-467e-abae-40d5f87d9e80)
![image](https://github.com/user-attachments/assets/34e27610-d79c-4c00-828a-3781aacd1674)
