### ISSUE TITLE
Motor position not reporting, motors spins indefinitely

### ISSUE THREAD

**Issue by ItsRebaseTime** [slimcdk/esphome-custom-components#16]
Hello,
I am working on IKEA roller blinds conversion to stepper motor with TMC2209. I configured everything as in examples, but the motor keeps spinning indefinitely and the `current_position` does not update with the actual position. Is there an issue with my wiring or GPIO selection? Position was reporting before the recent update. Tested various configurations of diag/index pins, the issue persists.
My ESP32 board: https://docs.m5stack.com/en/unit/poesp32
Connections are made with perfboard and some decent soldered wires.
Here is my configuration:

```
esphome:
  name: blinds
  friendly_name: Blinds
  on_boot:
    - tmc2209.configure:
        microsteps: 1
        interpolation: False
        enable_spreadcycle: False
        tcool_threshold: 1000 # SG can be triggered when speed exceeds this value
    - tmc2209.stallguard:
        threshold: 10 # SG is triggered if the SG value is lower than 2x threshold
    - tmc2209.currents:
        standstill_mode: normal
        irun: 31 # 16 for best microstep performance (16/32 = 1/2 maximum motor current)
        ihold: 31 # should be 0 to enable passive breaking
        tpowerdown: 0
        iholddelay: 0
    # - button.press: home_button # home right after boot

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  hardware_uart: UART1

ethernet:
  type: IP101
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO5

text_sensor:
  - platform: ethernet_info
    ip_address:
      name: "IP"
    mac_address:
      name: "MAC"
    dns_address:
      name: "DNS"

external_components:
  - source: github://slimcdk/esphome-custom-components
    components: [ tmc2209_hub, tmc2209, stepper ]

globals:
  - id: has_homed
    type: bool
    initial_value: "true"
    restore_value: False
  - id: blinds_bottom_pos
    type: int
    initial_value: '9999'
    restore_value: True
  - id: blinds_top_pos
    type: int
    initial_value: '0'
    restore_value: True

uart:
  id: tmc2209_uart
  rx_pin: GPIO17
  tx_pin: GPIO16
  baud_rate: 115200

tmc2209_hub:
  id: tmc_hub
  uart_id: tmc2209_uart

stepper:
  - platform: tmc2209
    id: driver
    tmc2209_hub_id: tmc_hub
    diag_pin: GPIO1
    index_pin: GPIO3
    max_speed: 500 steps/s
    acceleration: 100 steps/s^2
    deceleration: 100 steps/s^2
    address: 0x00
    # rsense: 110 mOhm
    vsense: False
    on_status:
      - logger.log:
          format: "Driver is reporting an update! (code %d)"
          args: ["code"]
      - if:
          condition:
            lambda: return code == tmc2209::DIAG_TRIGGERED;
          then:
            - logger.log: DIAG_TRIGGERED
      - if:
          condition:
            lambda: return code == tmc2209::DIAG_TRIGGER_CLEARED;
          then:
            - logger.log: DIAG_TRIGGER_CLEARED
      - if:
          condition:
            lambda: return code == tmc2209::RESET;
          then:
            - logger.log: RESET
      - if:
          condition:
            lambda: return code == tmc2209::RESET_CLEARED;
          then:
            - logger.log: RESET_CLEARED
      - if:
          condition:
            lambda: return code == tmc2209::DRIVER_ERROR;
          then:
            - logger.log: DRIVER_ERROR
      - if:
          condition:
            lambda: return code == tmc2209::DRIVER_ERROR_CLEARED;
          then:
            - logger.log: DRIVER_ERROR_CLEARED
    on_stall:
      - logger.log: "Motor stalled!"
      - if:
          condition:
            lambda: |-
              return !id(has_homed);
          then:
            - stepper.stop: driver
            - stepper.report_position:
                id: driver
                position: 0
            - globals.set:
                id: has_homed
                value: "true"
            - logger.log: "Homed"

button:
  - platform: template
    id: home_button
    name: "Home"
    on_press:
      - logger.log: "Going home!"
      - globals.set:
          id: has_homed
          value: "false"
      - stepper.set_target:
          id: driver
          target: -9999999
  - platform: template
    id: set_bottom_pos_button
    name: "Set bottom position"
    on_press:
      then:
        - globals.set: 
            id: blinds_bottom_pos
            value: !lambda 'return id(driver)->current_position;'
        - lambda: |-
            ESP_LOGD("Blinds", "Setting bottom position to: %d", id(driver)->current_position);
  - platform: template
    id: set_top_pos_button
    name: "Set top position"
    on_press:
      then:
        - globals.set: 
            id: blinds_top_pos
            value: !lambda 'return id(driver)->current_position;'
        - lambda: |-
            ESP_LOGD("Blinds", "Setting top position to: %d", id(driver)->current_position);

binary_sensor:
  - platform: template
    id: homed_status_sensor
    entity_category: DIAGNOSTIC
    name: "Homed status"
    lambda: |-
      return id(has_homed);

sensor:
  - platform: template
    entity_category: DIAGNOSTIC
    id: top_position_sensor
    name: "Top position"
    accuracy_decimals: 0
    unit_of_measurement: "steps"
    lambda: |-
      return id(blinds_top_pos);

  - platform: template
    entity_category: DIAGNOSTIC
    id: bottom_position_sensor
    name: "Bottom position"
    accuracy_decimals: 0
    unit_of_measurement: "steps"
    lambda: |-
      return id(blinds_bottom_pos);

  - platform: template
    entity_category: DIAGNOSTIC
    id: stepper_position_sensor
    name: "Position"
    unit_of_measurement: "steps"
    accuracy_decimals: 0
    update_interval: 250ms
    lambda: |-
      return id(driver)->current_position;

  - platform: tmc2209
    entity_category: DIAGNOSTIC
    internal: True
    type: stallguard_result
    name: Driver stallguard
    update_interval: 250ms
```
