### ISSUE TITLE
Cannot get the StallGuard feature to work

### ISSUE THREAD

**Issue by bfrigon** [slimcdk/esphome-custom-components#24]
Maybe i'm missing something but i cannot get the StallGuard feature to work.

The problem is that the DIAG pin always stay low, no matter what. Even if the motor is unplugged, it still not rise the DIAG pin which is should as it detects an open load.

I wired the TMC2209 for UART mode.
Here is my config :

```

esphome:  
  on_boot:

    # Configure stepper driver registers
    - tmc2209.configure:
        microsteps: 16
        interpolation: true
        enable_spreadcycle: False
    - tmc2209.stallguard:
        threshold: 50
    - tmc2209.currents:
        standstill_mode: freewheeling
        run_current: 350ma
        ihold: 0
        tpowerdown: 0
        iholddelay: 0

sensor:
  - platform: tmc2209
    type: stallguard_result
    name: Motor stallguard
    entity_category: diagnostic
    update_interval: 250ms
    filters:
      - delta: 1

stepper:
  - platform: tmc2209
    id: stepper_dispenser
    max_speed: 1000 steps/s
    acceleration: 5000 steps/s^2
    deceleration: 5000 steps/s^2
    address: 0x03
    rsense: 110 mOhm
    vsense: False
    ottrim: 0
    analog_current_scale: False
    enn_pin:
      number: 10
      mode: OUTPUT_OPEN_DRAIN
    diag_pin:
      number: 7
      mode: INPUT_PULLUP
    index_pin:
      number: 5
      mode: INPUT
    on_stall:
      - logger.log: "Motor stalled!"
      - stepper.stop: stepper_dispenser
```
